name: detector_placas
description: "Detector de placas vehiculares con YOLOv8"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP requests
  http: ^1.2.0
  
  # Image picker (camera y galería)
  image_picker: ^1.0.7
  
  # Permisos
  permission_handler: ^11.3.0
  
  # Iconos
  cupertino_icons: ^1.0.2

  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true